# Generated by Django 5.1.2 on 2024-11-03 08:05

import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_room_amenities_room_bed_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomimage",
            options={
                "ordering": ["-upload_date"],
                "verbose_name": "Room Image",
                "verbose_name_plural": "Room Images",
            },
        ),
        migrations.RemoveField(
            model_name="roomimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="roomimage",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="roomimage",
            name="room",
        ),
        migrations.AddField(
            model_name="roomimage",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="room_images/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="title",
            field=models.CharField(blank=True, max_length=100, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="upload_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Upload Date"
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="room_images/", verbose_name="Image"
            ),
        ),
        migrations.CreateModel(
            name="RoomGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Image"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.roomimage",
                        verbose_name="Image",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="bookings.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Gallery Image",
                "verbose_name_plural": "Room Gallery Images",
                "ordering": ["order", "-is_primary"],
                "unique_together": {("room", "image")},
            },
        ),
        migrations.AddField(
            model_name="room",
            name="images",
            field=models.ManyToManyField(
                related_name="rooms",
                through="bookings.RoomGallery",
                to="bookings.roomimage",
                verbose_name="Images",
            ),
        ),
    ]
