# Generated by Django 5.1.2 on 2024-11-03 08:21

import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0003_alter_roomimage_options_remove_roomimage_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="images",
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="gallery/", verbose_name="Image"
                    ),
                ),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="Title"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Image"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upload Date"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="bookings.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["order", "-upload_date"],
            },
        ),
        migrations.DeleteModel(
            name="RoomGallery",
        ),
        migrations.DeleteModel(
            name="RoomImage",
        ),
    ]
